kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: mysql-ns

spec:
  clusterIP: None # stop to be expose, used only internally by needed services
  selector:
    app: mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
